namespace MemReduct.Core;

public static class StrId
{
    public const uint TrayShow = 12;
    public const uint Settings = 4;
    public const uint Exit = 5;
    public const uint CleanMemory = 17;
    public const uint About = 10;
    public const uint GroupPhysical = 18;
    public const uint GroupPagefile = 19;
    public const uint GroupSystemCache = 20;
    public const uint ItemUsage = 21;
    public const uint ItemAvailable = 22;
    public const uint ItemTotal = 23;
    public const uint SettingsGeneral = 24;
    public const uint SettingsMemory = 25;
    public const uint SettingsAppearance = 26;
    public const uint SettingsTray = 27;
    public const uint TitleMemoryRegions = 31;
    public const uint TitleMemoryManagement = 32;
    public const uint TitleHotkeys = 33;
    public const uint ColorIndication = 35;
    public const uint BalloonTips = 37;
    public const uint AlwaysOnTop = 38;
    public const uint LoadOnStartup = 39;
    public const uint StartMinimized = 40;
    public const uint ConfirmCleaning = 41;
    public const uint LanguageHint = 44;
    public const uint WorkingSet = 45;
    public const uint SystemFileCache = 46;
    public const uint StandbyPriority0 = 47;
    public const uint StandbyList = 48;
    public const uint ModifiedList = 49;
    public const uint CombineMemoryLists = 50;
    public const uint RegistryCache = 95;
    public const uint ModifiedFileCache = 96;
    public const uint AutoCleanEnable = 51;
    public const uint AutoCleanInterval = 52;
    public const uint HotkeyClean = 53;
    public const uint WarningLevel = 64;
    public const uint DangerLevel = 65;
    public const uint ShowCleanResult = 71;
    public const uint Question = 72;
    public const uint NotificationSound = 84;
    public const uint TitleAdvanced = 85;
    public const uint AllowStandbyCleanup = 89;
    public const uint LogCleanResults = 90;
    public const uint StatusCleaned = 75;
    public const uint StatusNoPrivileges = 76;
    public const uint Theme = 91;
    public const uint ThemeSystem = 92;
    public const uint ThemeLight = 93;
    public const uint ThemeDark = 94;
    public const uint TrayPopUp1 = 14;  // Clean areas
    public const uint TrayPopUp2 = 15;  // Clean when above
    public const uint TrayPopUp3 = 16;  // Clean every
    public const uint TrayDisable = 13; // Disable
    public const uint TrayActionScHint = 66; // Single click:
    public const uint TrayActionMcHint = 67; // Middle click:
    public const uint TrayAction1 = 68; // Show / Hide
    public const uint TrayAction2 = 69; // Clean memory
    public const uint TrayAction3 = 70; // Open task manager
    public const uint Dashboard = 97;
    public const uint MinuteUnit = 98;
    public const uint HotkeyPrompt = 99;
    public const uint HotkeyHint = 100;
    public const uint Save = 101;
    public const uint Cancel = 102;
    public const uint HotkeyConflict = 103;
    public const uint Version = 104;
    public const uint AboutDescription = 105;
    public const uint Author = 106;
    public const uint UpstreamProject = 108;
    public const uint ProjectRepository = 109;
    public const uint RunAsAdministratorMessage = 110;
    public const uint RestartAsAdministrator = 111;
    public const uint CleaningFailed = 112;
    public const uint CleanupNotStarted = 113;
    public const uint FailedAreas = 114;
    public const uint NoSignificantMemory = 115;
    public const uint PartialCleanupResult = 116;
    public const uint NoCleanupAreasSelected = 117;
    public const uint CommandLineUsage = 118;
    public const uint CommandLinePartialFailure = 119;
    public const uint CommandLineFailure = 120;
    public const uint AdministratorRequired = 121;
    public const uint CommandLineHelpTitle = 122;
    public const uint CommandLineHelpShow = 123;
    public const uint CommandLineHelpClean = 124;
    public const uint CommandLineHelpFull = 125;
    public const uint TrayShowMemoryUsage = 126;
}
